from tkinter import *
root = Tk()
root.title("Пример меню на Python")
root.geometry("400x300")
main_menu = Menu()
file_menu = Menu(font=("Comic sans", 10, "bold"), tearoff=0, activebackground="red")
file_menu.add_command(label="New file")
file_menu.add_command(label="Save")
file_menu.add_command(label="Save as ")
file_menu.add_command(label="Open")
file_menu.add_separator()
file_menu.add_command(label="Exit")
main_menu.add_cascade(label="File", menu=file_menu)
edit_menu = Menu(font=("Comic sans", 10, "bold"), tearoff=0, activebackground="red")
edit_menu.add_command(label="Delete")
edit_menu.add_command(label="Add")
main_menu.add_cascade(label="Edit", menu=edit_menu)
view_menu = Menu(font=("Comic sans", 10, "bold"), tearoff=0, activebackground="red")
view_menu.add_command(label="Change view")
main_menu.add_cascade(label="View", menu=view_menu)
root.config(menu=main_menu)
root.mainloop()
